### ISSUE TITLE
Sage versions

### ISSUE THREAD

**Issue by siemvaessen** [markbrough/sage-iati#1]
Is this suitable for _any_ Sage version?

**Comment by markbrough** [comment]
Good question, I'm not sure. I guess so, given that you just generate a certain (standard) report out of Sage and then upload that data. So if that standard report is not available in all versions then you should be able to create it relatively easily.

**Comment by markbrough** [comment]
Will check with our Finance person and upload an example spreadsheet

**Comment by markbrough** [comment]
@siemvaessen -- just got the answer to this. This is the version we use for our accounts:
Sage 50 Accounts Plus 2011
Version: 17.0.15.208

To get the data out of Sage:
- select the `Company` tab (bottom left), then `Reports` (from the top)
- select `Nominal Activity` and then `Nominal Activity` again
- select accounts over `4000` (this may be different for different systems, but I understand that this is important to excludes certain accounts to avoid double-counting)
- export to Excel 2007

**Comment by siemvaessen** [comment]
Hi @markbrough - we willl liasion this back. just noticed your feedback :-)
