### ISSUE TITLE
Version 21-5-9.201

### ISSUE THREAD

**Issue by siemvaessen** [markbrough/sage-iati#7]
Hi,

We have a party running SAGE5- - V 21-5-9.201 => compatible?

Thanks, Siem

**Comment by markbrough** [comment]
Not sure - I would guess yes, but you would possibly have to construct a custom export or rejig the data before parsing. Maybe try it out and see?

**Comment by siemvaessen** [comment]
Probably yes. But we have a worklfow in place with custom transform script. I was just interested to see how off the shefl sage-iati would be. Thanks @markbrough
